image: debian:stretch

stages:
  - test
  - deploy

variables:
  ANDROID_HOME: /usr/lib/android-sdk
  DEBIAN_FRONTEND: noninteractive

before_script:
  - printf 'APT::Install-Recommends "0";\nAPT::Install-Suggests "0";\n'
      > /etc/apt/apt.conf.d/99no-install-recommends
  - printf 'APT::Acquire::Retries "20";\n'
      > /etc/apt/apt.conf.d/99acquire-retries
  - printf 'APT::Get::Assume-Yes "true";\n'
      > /etc/apt/apt.conf.d/99assumeyes
  - sed -i 's, main$, main contrib,' /etc/apt/sources.list
  - apt-get update
  - apt-get upgrade
  - apt-get install git
  - apt-get install --install-recommends
        android-sdk
        android-sdk-platform-23
        libgradle-android-plugin-java
        strip-nondeterminism

build_on_debian:
  stage: test
  except:
    - gh-pages
  script:
    - gradle jarRelease
    - for f in build/libs/*.*; do strip-nondeterminism $f; done
    - for f in build/libs/*.*; do sha256sum $f; done
  artifacts:
    name: "${CI_PROJECT_PATH}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_${CI_JOB_NAME}"
    paths:
      - build/docs
      - build/libs
    expire_in: 1 week
    when: on_success
  after_script:
    - echo "Download debug artifacts from https://gitlab.com/${CI_PROJECT_PATH}/-/jobs"

pages:
  stage: deploy
  only:
    - master
  artifacts:
    paths:
      - public
  script:
    - gradle javadoc
    - test -d public || mkdir public
    - cp -a build/docs/javadoc/* public/
