sudo: true
language: android

jdk:
  # the release build infrastructure uses OpenJDK from Debian
  - openjdk7
  # many developers use the Oracle JDK
  # (sometimes Travis cannot reliably start the emulator with these)
  - oraclejdk8
  - oraclejdk7

before_install:
  - sudo add-apt-repository ppa:guardianproject/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq strip-nondeterminism libarchive-zip-perl

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
  licenses:
    # only approve the free software licenses
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'

script:
  # run release build script
  - ./make-release-build

after_failure:
  - find * -name lint-results.xml | xargs cat
